# 0. ConfigMap containing your init SQL
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: iit-dev
data:
  init-user.sql: |
    -- create database if absent
    CREATE DATABASE IF NOT EXISTS gamedb;
    -- ensure the 'user' can connect from any host
    CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON gamedb.* TO 'user'@'%';
    FLUSH PRIVILEGES;

---

# 1. Namespace (no-op if already exists)
apiVersion: v1
kind: Namespace
metadata:
  name: iit-dev

---

# 2. PVC for MySQL Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: iit-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---

# 3. MySQL Deployment (with initdb volume mount)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: iit-dev
  labels:
    app: game-mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: game-mysql
  template:
    metadata:
      labels:
        app: game-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: gamedb
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
        - name: init-scripts
          configMap:
            name: mysql-init-scripts

---

# 4. MySQL Service (unchanged)
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: iit-dev
  labels:
    app: game-mysql
spec:
  type: ClusterIP
  selector:
    app: game-mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
