# Namespace (only needed once per cluster)
apiVersion: v1
kind: Namespace
metadata:
  name: iit-dev

---

# Deployment for Analytics Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  namespace: iit-dev  # ✅ Scoped to namespace for isolation
  labels:
    app: analytics-api
spec:
  replicas: 1  # ✅ Cost-optimized for coursework/free-tier
  selector:
    matchLabels:
      app: analytics-api
  template:
    metadata:
      labels:
        app: analytics-api
    spec:
      imagePullSecrets:
        - name: dockerhub-secret  # Optional, if you use private Docker Hub
      containers:
        - name: analytics-api
          image: nuviii/analytics-service:latest  # ✅ Pulls from Docker Hub
          imagePullPolicy: Always                  # ✅ Always pull latest image
          ports:
            - containerPort: 8087
              protocol: TCP
          env:
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_USER
              value: default
            - name: CLICKHOUSE_PASSWORD
              value: mypassword123
              # ⚠️ For production, consider Kubernetes Secret for password
          resources:  # ✅ Cloud limits to prevent overuse
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always

---

# Service for Analytics Service
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: iit-dev
  labels:
    app: analytics-api
spec:
  type: ClusterIP  # ✅ Suitable for Ingress routing in EKS
  selector:
    app: analytics-api
  ports:
    - protocol: TCP
      port: 8087        # ✅ Exposed port on the service
      targetPort: 8087  # ✅ Matches containerPort in the Deployment

---

# Ingress for Analytics Service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-ingress
  namespace: iit-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: lugx.local
      http:
        paths:
          - path: /api/analytics/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: analytics-service
                port:
                  number: 8087
