# Namespace
apiVersion: v1
kind: Namespace
metadata: 
  name: iit-dev
 
---

# Deployment (Blue)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-blue
  namespace: iit-dev
  labels:
    app: game-service
    version: blue
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: game-service
      version: blue
  template:
    metadata:
      labels:
        app: game-service
        version: blue
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: game-service
          image: nuviii/game-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "mysql+pymysql://root:Navo%402002@34.46.253.164:3306/gamedb"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always

---

# Stable Service (routes to blue or green)
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: iit-dev
  labels:
    app: game-service
spec:
  type: ClusterIP
  selector:
    app: game-service
    version: blue    # 🔁 Change to green in CI/CD when switching
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085

---

# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  namespace: iit-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: gameservice.lugx.iit
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game-service
                port:
                  number: 8085
