name: EKS CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Kubernetes Services to EKS (Blue-Green)
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: 2506634_lugx-cloud
      REGION: us-east-1
      DEPLOY_TARGET: green  # 🔁 Change to blue to switch traffic

    steps:
      - name: ✅ Checkout source code
        uses: actions/checkout@v4

      - name: 🧠 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: arn:aws:iam::221119316828:role/GitHubActionsEKSRole
          role-session-name: GitHubActionsSession

      - name: 🔍 Debug AWS identity
        run: aws sts get-caller-identity

      - name: 📡 Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

      - name: 🧪 Validate kubeconfig
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: 🏗️ Deploy ClickHouse (stateful, shared across envs)
        run: |
          echo "Deploying ClickHouse..."
          kubectl apply -f clickhouse/k8clickhouse.yaml

      - name: 🚀 Deploy selected environment (${{ env.DEPLOY_TARGET }})
        run: |
          echo "Deploying from: k8${{ env.DEPLOY_TARGET }}/"
          kubectl apply -f k8${{ env.DEPLOY_TARGET }}/

      - name: 🔁 Patch Services to point to $DEPLOY_TARGET
        run: |
          echo "Switching service selectors to: $DEPLOY_TARGET"

          kubectl patch service frontend-service -n iit-dev \
            --type=merge \
            -p "{\"spec\":{\"selector\":{\"app\":\"frontend\",\"version\":\"${DEPLOY_TARGET}\"}}}"

          kubectl patch service game-service -n iit-dev \
            --type=merge \
            -p "{\"spec\":{\"selector\":{\"app\":\"game-service\",\"version\":\"${DEPLOY_TARGET}\"}}}"

          kubectl patch service order-service -n iit-dev \
            --type=merge \
            -p "{\"spec\":{\"selector\":{\"app\":\"order-service\",\"version\":\"${DEPLOY_TARGET}\"}}}"

          kubectl patch service analytics-service -n iit-dev \
            --type=merge \
            -p "{\"spec\":{\"selector\":{\"app\":\"analytics-service\",\"version\":\"${DEPLOY_TARGET}\"}}}"

      - name: ✅ Verify deployed pods
        run: kubectl get pods -A
