name: GKE CI/CD Deployment (Blue-Green)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Which environment to deploy?"
        required: true
        default: "green"
        type: choice
        options:
          - blue
          - green

jobs:
  deploy:
    name: Deploy to GKE with Blue-Green
    runs-on: ubuntu-latest

    env:
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_LOCATION: ${{ secrets.GKE_LOCATION }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      DEPLOY_TARGET: ${{ github.event.inputs.deploy_target || 'green' }}

    steps:
      - name:  Checkout source code
        uses: actions/checkout@v4

      - name:  Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name:  Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name:  Configure gcloud for GKE
        run: |
          gcloud config set container/use_application_default_credentials true
          gcloud container clusters get-credentials "$GKE_CLUSTER" \
            --region "$GKE_LOCATION" \
            --project "$GCP_PROJECT_ID"

      - name:  Verify GKE context
        run: |
          kubectl config current-context
          kubectl get nodes

      - name:  Deploy ClickHouse (shared component)
        run: |
          echo "Deploying ClickHouse..."
          kubectl apply -f clickhouse/k8clickhouse.yaml

      - name:  Deploy to selected environment (${{ env.DEPLOY_TARGET }})
        run: |
          echo "Applying manifests from: k8${{ env.DEPLOY_TARGET }}/"
          kubectl apply -f k8${{ env.DEPLOY_TARGET }}/

      - name:  Patch services to target ${{ env.DEPLOY_TARGET }}
        run: |
          echo "Routing traffic to version: $DEPLOY_TARGET"

          kubectl patch service frontend-service -n iit-dev \
            --type=merge \
            -p "{\"spec\":{\"selector\":{\"app\":\"frontend\",\"version\":\"${DEPLOY_TARGET}\"}}}"

          kubectl patch service game-service -n iit-dev \
            --type=merge \
            -p "{\"spec\":{\"selector\":{\"app\":\"game-service\",\"version\":\"${DEPLOY_TARGET}\"}}}"

          kubectl patch service order-service -n iit-dev \
            --type=merge \
            -p "{\"spec\":{\"selector\":{\"app\":\"order-service\",\"version\":\"${DEPLOY_TARGET}\"}}}"

          kubectl patch service analytics-service -n iit-dev \
            --type=merge \
            -p "{\"spec\":{\"selector\":{\"app\":\"analytics-service\",\"version\":\"${DEPLOY_TARGET}\"}}}"

      - name:  List all pods after deployment
        run: kubectl get pods -A
