name: EKS CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Kubernetes Services to EKS
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: 2506634_lugx-cloud
      REGION: us-east-1

    steps:
      - name: ✅ Checkout source code
        uses: actions/checkout@v4

      - name: 🧠 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: arn:aws:iam::221119316828:role/GitHubActionsEKSRole
          role-session-name: GitHubActionsSession
          # ✅ external-id REMOVED because it's invalid for this action

      - name: 🔍 Debug AWS identity
        run: aws sts get-caller-identity

      - name: 📡 Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

      - name: 🧪 Validate kubeconfig
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: 🚀 Deploy all microservices
        run: |
          echo "Applying frontend manifests..."
          kubectl apply -f frontend/

          echo "Applying game-service manifests..."
          kubectl apply -f game-service/

          echo "Applying order-service manifests..."
          kubectl apply -f order-service/

          echo "Applying clickhouse manifests..."
          kubectl apply -f clickhouse/

          echo "Applying analytics-service manifests..."
          kubectl apply -f analytics-service/

      - name: ✅ Verify deployed pods
        run: kubectl get pods -A
